// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: ability.proto

package valorant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Debuff int32

const (
	Debuff_CONCUSS   Debuff = 0
	Debuff_FLASH     Debuff = 1
	Debuff_KNOCKBACK Debuff = 2
)

// Enum value maps for Debuff.
var (
	Debuff_name = map[int32]string{
		0: "CONCUSS",
		1: "FLASH",
		2: "KNOCKBACK",
	}
	Debuff_value = map[string]int32{
		"CONCUSS":   0,
		"FLASH":     1,
		"KNOCKBACK": 2,
	}
)

func (x Debuff) Enum() *Debuff {
	p := new(Debuff)
	*p = x
	return p
}

func (x Debuff) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Debuff) Descriptor() protoreflect.EnumDescriptor {
	return file_ability_proto_enumTypes[0].Descriptor()
}

func (Debuff) Type() protoreflect.EnumType {
	return &file_ability_proto_enumTypes[0]
}

func (x Debuff) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Debuff.Descriptor instead.
func (Debuff) EnumDescriptor() ([]byte, []int) {
	return file_ability_proto_rawDescGZIP(), []int{0}
}

type Ability struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Cost            int32                  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	CooldownSeconds int32                  `protobuf:"varint,4,opt,name=cooldown_seconds,json=cooldownSeconds,proto3" json:"cooldown_seconds,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	WindupSeconds   float32                `protobuf:"fixed32,6,opt,name=windup_seconds,json=windupSeconds,proto3" json:"windup_seconds,omitempty"`
	Damage          int32                  `protobuf:"varint,7,opt,name=damage,proto3" json:"damage,omitempty"`
	DebuffApplied   string                 `protobuf:"bytes,8,opt,name=debuff_applied,json=debuffApplied,proto3" json:"debuff_applied,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Ability) Reset() {
	*x = Ability{}
	mi := &file_ability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ability) ProtoMessage() {}

func (x *Ability) ProtoReflect() protoreflect.Message {
	mi := &file_ability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ability.ProtoReflect.Descriptor instead.
func (*Ability) Descriptor() ([]byte, []int) {
	return file_ability_proto_rawDescGZIP(), []int{0}
}

func (x *Ability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ability) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Ability) GetCooldownSeconds() int32 {
	if x != nil {
		return x.CooldownSeconds
	}
	return 0
}

func (x *Ability) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Ability) GetWindupSeconds() float32 {
	if x != nil {
		return x.WindupSeconds
	}
	return 0
}

func (x *Ability) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *Ability) GetDebuffApplied() string {
	if x != nil {
		return x.DebuffApplied
	}
	return ""
}

var File_ability_proto protoreflect.FileDescriptor

const file_ability_proto_rawDesc = "" +
	"\n" +
	"\rability.proto\"\x8f\x02\n" +
	"\aAbility\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x05R\x04cost\x12)\n" +
	"\x10cooldown_seconds\x18\x04 \x01(\x05R\x0fcooldownSeconds\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSeconds\x12%\n" +
	"\x0ewindup_seconds\x18\x06 \x01(\x02R\rwindupSeconds\x12\x16\n" +
	"\x06damage\x18\a \x01(\x05R\x06damage\x12%\n" +
	"\x0edebuff_applied\x18\b \x01(\tR\rdebuffApplied*/\n" +
	"\x06Debuff\x12\v\n" +
	"\aCONCUSS\x10\x00\x12\t\n" +
	"\x05FLASH\x10\x01\x12\r\n" +
	"\tKNOCKBACK\x10\x02B$Z\"match-sim/internal/domain/valorantb\x06proto3"

var (
	file_ability_proto_rawDescOnce sync.Once
	file_ability_proto_rawDescData []byte
)

func file_ability_proto_rawDescGZIP() []byte {
	file_ability_proto_rawDescOnce.Do(func() {
		file_ability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ability_proto_rawDesc), len(file_ability_proto_rawDesc)))
	})
	return file_ability_proto_rawDescData
}

var file_ability_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ability_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ability_proto_goTypes = []any{
	(Debuff)(0),     // 0: Debuff
	(*Ability)(nil), // 1: Ability
}
var file_ability_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ability_proto_init() }
func file_ability_proto_init() {
	if File_ability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ability_proto_rawDesc), len(file_ability_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ability_proto_goTypes,
		DependencyIndexes: file_ability_proto_depIdxs,
		EnumInfos:         file_ability_proto_enumTypes,
		MessageInfos:      file_ability_proto_msgTypes,
	}.Build()
	File_ability_proto = out.File
	file_ability_proto_goTypes = nil
	file_ability_proto_depIdxs = nil
}
