// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: agent.proto

package valorant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRole int32

const (
	AgentRole_CONTROLLER AgentRole = 0
	AgentRole_DUELIST    AgentRole = 1
	AgentRole_INITIATOR  AgentRole = 2
	AgentRole_SENTINEL   AgentRole = 3
)

// Enum value maps for AgentRole.
var (
	AgentRole_name = map[int32]string{
		0: "CONTROLLER",
		1: "DUELIST",
		2: "INITIATOR",
		3: "SENTINEL",
	}
	AgentRole_value = map[string]int32{
		"CONTROLLER": 0,
		"DUELIST":    1,
		"INITIATOR":  2,
		"SENTINEL":   3,
	}
)

func (x AgentRole) Enum() *AgentRole {
	p := new(AgentRole)
	*p = x
	return p
}

func (x AgentRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentRole) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (AgentRole) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x AgentRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentRole.Descriptor instead.
func (AgentRole) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type AgentName int32

const (
	AgentName_ASTRA     AgentName = 0
	AgentName_BREACH    AgentName = 1
	AgentName_BRIMSTONE AgentName = 2
	AgentName_CHAMBER   AgentName = 3
	AgentName_CLOVE     AgentName = 4
	AgentName_HARBOR    AgentName = 5
	AgentName_ISO       AgentName = 6
	AgentName_JETT      AgentName = 7
	AgentName_KAYO      AgentName = 8
	AgentName_KILLJOY   AgentName = 9
	AgentName_NEON      AgentName = 10
	AgentName_RAZE      AgentName = 11
	AgentName_REYNA     AgentName = 12
	AgentName_SAGE      AgentName = 13
	AgentName_SKYE      AgentName = 14
	AgentName_TEJO      AgentName = 15
	AgentName_VIPER     AgentName = 16
	AgentName_WAYLAY    AgentName = 17
	AgentName_YORU      AgentName = 18
)

// Enum value maps for AgentName.
var (
	AgentName_name = map[int32]string{
		0:  "ASTRA",
		1:  "BREACH",
		2:  "BRIMSTONE",
		3:  "CHAMBER",
		4:  "CLOVE",
		5:  "HARBOR",
		6:  "ISO",
		7:  "JETT",
		8:  "KAYO",
		9:  "KILLJOY",
		10: "NEON",
		11: "RAZE",
		12: "REYNA",
		13: "SAGE",
		14: "SKYE",
		15: "TEJO",
		16: "VIPER",
		17: "WAYLAY",
		18: "YORU",
	}
	AgentName_value = map[string]int32{
		"ASTRA":     0,
		"BREACH":    1,
		"BRIMSTONE": 2,
		"CHAMBER":   3,
		"CLOVE":     4,
		"HARBOR":    5,
		"ISO":       6,
		"JETT":      7,
		"KAYO":      8,
		"KILLJOY":   9,
		"NEON":      10,
		"RAZE":      11,
		"REYNA":     12,
		"SAGE":      13,
		"SKYE":      14,
		"TEJO":      15,
		"VIPER":     16,
		"WAYLAY":    17,
		"YORU":      18,
	}
)

func (x AgentName) Enum() *AgentName {
	p := new(AgentName)
	*p = x
	return p
}

func (x AgentName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentName) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (AgentName) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x AgentName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentName.Descriptor instead.
func (AgentName) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          AgentName              `protobuf:"varint,2,opt,name=name,proto3,enum=AgentName" json:"name,omitempty"`
	Role          AgentRole              `protobuf:"varint,3,opt,name=role,proto3,enum=AgentRole" json:"role,omitempty"`
	Abilities     []*Ability             `protobuf:"bytes,4,rep,name=abilities,proto3" json:"abilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Agent) GetName() AgentName {
	if x != nil {
		return x.Name
	}
	return AgentName_ASTRA
}

func (x *Agent) GetRole() AgentRole {
	if x != nil {
		return x.Role
	}
	return AgentRole_CONTROLLER
}

func (x *Agent) GetAbilities() []*Ability {
	if x != nil {
		return x.Abilities
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x1a\rability.proto\"\x7f\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\x0e2\n" +
	".AgentNameR\x04name\x12\x1e\n" +
	"\x04role\x18\x03 \x01(\x0e2\n" +
	".AgentRoleR\x04role\x12&\n" +
	"\tabilities\x18\x04 \x03(\v2\b.AbilityR\tabilities*E\n" +
	"\tAgentRole\x12\x0e\n" +
	"\n" +
	"CONTROLLER\x10\x00\x12\v\n" +
	"\aDUELIST\x10\x01\x12\r\n" +
	"\tINITIATOR\x10\x02\x12\f\n" +
	"\bSENTINEL\x10\x03*\xdd\x01\n" +
	"\tAgentName\x12\t\n" +
	"\x05ASTRA\x10\x00\x12\n" +
	"\n" +
	"\x06BREACH\x10\x01\x12\r\n" +
	"\tBRIMSTONE\x10\x02\x12\v\n" +
	"\aCHAMBER\x10\x03\x12\t\n" +
	"\x05CLOVE\x10\x04\x12\n" +
	"\n" +
	"\x06HARBOR\x10\x05\x12\a\n" +
	"\x03ISO\x10\x06\x12\b\n" +
	"\x04JETT\x10\a\x12\b\n" +
	"\x04KAYO\x10\b\x12\v\n" +
	"\aKILLJOY\x10\t\x12\b\n" +
	"\x04NEON\x10\n" +
	"\x12\b\n" +
	"\x04RAZE\x10\v\x12\t\n" +
	"\x05REYNA\x10\f\x12\b\n" +
	"\x04SAGE\x10\r\x12\b\n" +
	"\x04SKYE\x10\x0e\x12\b\n" +
	"\x04TEJO\x10\x0f\x12\t\n" +
	"\x05VIPER\x10\x10\x12\n" +
	"\n" +
	"\x06WAYLAY\x10\x11\x12\b\n" +
	"\x04YORU\x10\x12B$Z\"match-sim/internal/domain/valorantb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agent_proto_goTypes = []any{
	(AgentRole)(0),  // 0: AgentRole
	(AgentName)(0),  // 1: AgentName
	(*Agent)(nil),   // 2: Agent
	(*Ability)(nil), // 3: Ability
}
var file_agent_proto_depIdxs = []int32{
	1, // 0: Agent.name:type_name -> AgentName
	0, // 1: Agent.role:type_name -> AgentRole
	3, // 2: Agent.abilities:type_name -> Ability
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_ability_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
