// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: weapon.proto

package valorant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeaponType int32

const (
	WeaponType_SIDEARM      WeaponType = 0
	WeaponType_SMG          WeaponType = 1
	WeaponType_SHOTGUN      WeaponType = 2
	WeaponType_RIFLE        WeaponType = 3
	WeaponType_SNIPER_RIFLE WeaponType = 4
	WeaponType_MACHINE_GUN  WeaponType = 5
	WeaponType_MELEE        WeaponType = 6
)

// Enum value maps for WeaponType.
var (
	WeaponType_name = map[int32]string{
		0: "SIDEARM",
		1: "SMG",
		2: "SHOTGUN",
		3: "RIFLE",
		4: "SNIPER_RIFLE",
		5: "MACHINE_GUN",
		6: "MELEE",
	}
	WeaponType_value = map[string]int32{
		"SIDEARM":      0,
		"SMG":          1,
		"SHOTGUN":      2,
		"RIFLE":        3,
		"SNIPER_RIFLE": 4,
		"MACHINE_GUN":  5,
		"MELEE":        6,
	}
)

func (x WeaponType) Enum() *WeaponType {
	p := new(WeaponType)
	*p = x
	return p
}

func (x WeaponType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeaponType) Descriptor() protoreflect.EnumDescriptor {
	return file_weapon_proto_enumTypes[0].Descriptor()
}

func (WeaponType) Type() protoreflect.EnumType {
	return &file_weapon_proto_enumTypes[0]
}

func (x WeaponType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeaponType.Descriptor instead.
func (WeaponType) EnumDescriptor() ([]byte, []int) {
	return file_weapon_proto_rawDescGZIP(), []int{0}
}

type WeaponName int32

const (
	WeaponName_KNIFE    WeaponName = 0
	WeaponName_CLASSIC  WeaponName = 1
	WeaponName_SHORTY   WeaponName = 2
	WeaponName_FRENZY   WeaponName = 3
	WeaponName_GHOST    WeaponName = 4
	WeaponName_SHERIFF  WeaponName = 5
	WeaponName_STINGER  WeaponName = 6
	WeaponName_SPECTRE  WeaponName = 7
	WeaponName_BUCKY    WeaponName = 8
	WeaponName_JUDGE    WeaponName = 9
	WeaponName_BULLDOG  WeaponName = 10
	WeaponName_GUARDIAN WeaponName = 11
	WeaponName_PHANTOM  WeaponName = 12
	WeaponName_VANDAL   WeaponName = 13
	WeaponName_MARSHAL  WeaponName = 14
	WeaponName_OUTLAW   WeaponName = 15
	WeaponName_OPERATOR WeaponName = 16
	WeaponName_ARES     WeaponName = 17
	WeaponName_ODIN     WeaponName = 18
)

// Enum value maps for WeaponName.
var (
	WeaponName_name = map[int32]string{
		0:  "KNIFE",
		1:  "CLASSIC",
		2:  "SHORTY",
		3:  "FRENZY",
		4:  "GHOST",
		5:  "SHERIFF",
		6:  "STINGER",
		7:  "SPECTRE",
		8:  "BUCKY",
		9:  "JUDGE",
		10: "BULLDOG",
		11: "GUARDIAN",
		12: "PHANTOM",
		13: "VANDAL",
		14: "MARSHAL",
		15: "OUTLAW",
		16: "OPERATOR",
		17: "ARES",
		18: "ODIN",
	}
	WeaponName_value = map[string]int32{
		"KNIFE":    0,
		"CLASSIC":  1,
		"SHORTY":   2,
		"FRENZY":   3,
		"GHOST":    4,
		"SHERIFF":  5,
		"STINGER":  6,
		"SPECTRE":  7,
		"BUCKY":    8,
		"JUDGE":    9,
		"BULLDOG":  10,
		"GUARDIAN": 11,
		"PHANTOM":  12,
		"VANDAL":   13,
		"MARSHAL":  14,
		"OUTLAW":   15,
		"OPERATOR": 16,
		"ARES":     17,
		"ODIN":     18,
	}
)

func (x WeaponName) Enum() *WeaponName {
	p := new(WeaponName)
	*p = x
	return p
}

func (x WeaponName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeaponName) Descriptor() protoreflect.EnumDescriptor {
	return file_weapon_proto_enumTypes[1].Descriptor()
}

func (WeaponName) Type() protoreflect.EnumType {
	return &file_weapon_proto_enumTypes[1]
}

func (x WeaponName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeaponName.Descriptor instead.
func (WeaponName) EnumDescriptor() ([]byte, []int) {
	return file_weapon_proto_rawDescGZIP(), []int{1}
}

type Weapon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WeaponType             `protobuf:"varint,1,opt,name=type,proto3,enum=WeaponType" json:"type,omitempty"`
	Name          WeaponName             `protobuf:"varint,2,opt,name=name,proto3,enum=WeaponName" json:"name,omitempty"`
	Cost          uint32                 `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weapon) Reset() {
	*x = Weapon{}
	mi := &file_weapon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weapon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weapon) ProtoMessage() {}

func (x *Weapon) ProtoReflect() protoreflect.Message {
	mi := &file_weapon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weapon.ProtoReflect.Descriptor instead.
func (*Weapon) Descriptor() ([]byte, []int) {
	return file_weapon_proto_rawDescGZIP(), []int{0}
}

func (x *Weapon) GetType() WeaponType {
	if x != nil {
		return x.Type
	}
	return WeaponType_SIDEARM
}

func (x *Weapon) GetName() WeaponName {
	if x != nil {
		return x.Name
	}
	return WeaponName_KNIFE
}

func (x *Weapon) GetCost() uint32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

var File_weapon_proto protoreflect.FileDescriptor

const file_weapon_proto_rawDesc = "" +
	"\n" +
	"\fweapon.proto\"^\n" +
	"\x06Weapon\x12\x1f\n" +
	"\x04type\x18\x01 \x01(\x0e2\v.WeaponTypeR\x04type\x12\x1f\n" +
	"\x04name\x18\x02 \x01(\x0e2\v.WeaponNameR\x04name\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\rR\x04cost*h\n" +
	"\n" +
	"WeaponType\x12\v\n" +
	"\aSIDEARM\x10\x00\x12\a\n" +
	"\x03SMG\x10\x01\x12\v\n" +
	"\aSHOTGUN\x10\x02\x12\t\n" +
	"\x05RIFLE\x10\x03\x12\x10\n" +
	"\fSNIPER_RIFLE\x10\x04\x12\x0f\n" +
	"\vMACHINE_GUN\x10\x05\x12\t\n" +
	"\x05MELEE\x10\x06*\xf3\x01\n" +
	"\n" +
	"WeaponName\x12\t\n" +
	"\x05KNIFE\x10\x00\x12\v\n" +
	"\aCLASSIC\x10\x01\x12\n" +
	"\n" +
	"\x06SHORTY\x10\x02\x12\n" +
	"\n" +
	"\x06FRENZY\x10\x03\x12\t\n" +
	"\x05GHOST\x10\x04\x12\v\n" +
	"\aSHERIFF\x10\x05\x12\v\n" +
	"\aSTINGER\x10\x06\x12\v\n" +
	"\aSPECTRE\x10\a\x12\t\n" +
	"\x05BUCKY\x10\b\x12\t\n" +
	"\x05JUDGE\x10\t\x12\v\n" +
	"\aBULLDOG\x10\n" +
	"\x12\f\n" +
	"\bGUARDIAN\x10\v\x12\v\n" +
	"\aPHANTOM\x10\f\x12\n" +
	"\n" +
	"\x06VANDAL\x10\r\x12\v\n" +
	"\aMARSHAL\x10\x0e\x12\n" +
	"\n" +
	"\x06OUTLAW\x10\x0f\x12\f\n" +
	"\bOPERATOR\x10\x10\x12\b\n" +
	"\x04ARES\x10\x11\x12\b\n" +
	"\x04ODIN\x10\x12B$Z\"match-sim/internal/domain/valorantb\x06proto3"

var (
	file_weapon_proto_rawDescOnce sync.Once
	file_weapon_proto_rawDescData []byte
)

func file_weapon_proto_rawDescGZIP() []byte {
	file_weapon_proto_rawDescOnce.Do(func() {
		file_weapon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weapon_proto_rawDesc), len(file_weapon_proto_rawDesc)))
	})
	return file_weapon_proto_rawDescData
}

var file_weapon_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_weapon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_weapon_proto_goTypes = []any{
	(WeaponType)(0), // 0: WeaponType
	(WeaponName)(0), // 1: WeaponName
	(*Weapon)(nil),  // 2: Weapon
}
var file_weapon_proto_depIdxs = []int32{
	0, // 0: Weapon.type:type_name -> WeaponType
	1, // 1: Weapon.name:type_name -> WeaponName
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_weapon_proto_init() }
func file_weapon_proto_init() {
	if File_weapon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weapon_proto_rawDesc), len(file_weapon_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_weapon_proto_goTypes,
		DependencyIndexes: file_weapon_proto_depIdxs,
		EnumInfos:         file_weapon_proto_enumTypes,
		MessageInfos:      file_weapon_proto_msgTypes,
	}.Build()
	File_weapon_proto = out.File
	file_weapon_proto_goTypes = nil
	file_weapon_proto_depIdxs = nil
}
